import type { EvidenceProvider } from "../../agent/evidence";
import type { RequestContext } from "../../contracts/context";

import type { RagflowEvidenceStore } from "./evidence-store";

/**
 * Create an `EvidenceProvider` backed by a ragflow evidence store.
 *
 * This is used to verify `citationId` generated by the ragflow adapter:
 * - evidence lookup is isolated by `tenantId`
 * - and by `projectId` when `ctx.projectId` is provided
 */
export const createRagflowEvidenceProvider = <TContext extends RequestContext>(
  store: RagflowEvidenceStore
): EvidenceProvider<TContext> => {
  return {
    async getEvidence(ctx, citationId) {
      return store.get(ctx, citationId);
    }
  };
};
